### ISSUE TITLE
Value Error for dataset with length greater than 255

### ISSUE THREAD

**Issue by codefusser** [jtreeves/regressions_library#1]
Recently, I started to use the regressions library for data modelling but realized that it may only support data size with length less than 255. When a dataset of size 400 was analyzed to determine the suitable model with 

`model_data = sinusoidal_model(data_list)`

the value error returned is stated below:

_ValueError: First argument and second argument must contain the same amount of lists_

Actually, the two x-y pair has equal lengths i.e. 400 * 400 

But to circumvent the issue, the dataset was reduced to 254 and any length equal to or less than that works.

What might be wrong?

Thanks!

**Comment by jtreeves** [comment]
Thanks so much reporting this issue, and thanks so much for using this regressions library! Apologies for my delayed response. I will look into this over the weekend, and I hope to get the issue resolved before the end of Sunday. Since I have some preliminary ideas about what may be causing the issue, I anticipate it will only require a simple patch to fix, and I do not anticipate that it will take longer than this weekend to resolve. I will message you when it's resolved or if I run into any obstacles that may delay its resolution. Thanks for your patience!

**Comment by codefusser** [comment]
I found a fix 👍 ! 
Python seems to prefer using the mathematical comparison operators when comparing numerical values (objects) to when comparing non-numerical objects. So replaced `is not` with `!=` for the numerical operations in `errors/matrices.py` file.

**Comment by jtreeves** [comment]
Great minds think alike! I just deployed a patch fix to PyPI (`2.1.1`) with all `is not` expressions replaced with `!=` for numerical operations within the `errors` folder (there were also some in `vectors.py` that were throwing things off). I also added a new test set containing 1,000 coordinate pairs to confirm the library can handle large data sets. Thanks for all your help! Please let me know if you notice any other glitches 😄
